# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "tun" "bridge" "veth" "wireguard" ];
  boot.extraModulePackages = [ ];


  # Root

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/77044032-08ab-48bd-8961-331e34fdfb11";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E016-3485";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5e7a9c5c-1137-4882-9a70-766477d888d9"; }
    ];


  # Share

  fileSystems."/mnt/share" =
    { device = "/dev/disk/by-uuid/51a551fa-d1ba-4c83-8ad5-bfcab4496f29";
      fsType = "btrfs";
    };


  # Data

  fileSystems."/mnt/data" =
    { device = "/dev/disk/by-uuid/acb26053-df19-42f5-90b7-9e29079db53c";
      fsType = "ext4";
    };

  services.btrfs.autoScrub.enable = true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
